# Generated by Django 5.2 on 2025-04-11 02:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('fecha_lanzamiento', models.DateField()),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='consolas/')),
                ('es_actual', models.BooleanField(default=True)),
                ('especificaciones', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Consolas',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PAG', 'Pagado'), ('ENV', 'Enviado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='PEN', max_length=3)),
                ('direccion_envio', models.TextField()),
                ('metodo_pago', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(max_length=20, unique=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('ACT', 'Acción'), ('AVT', 'Aventura'), ('RPG', 'RPG'), ('DEP', 'Deportes'), ('FGT', 'Lucha'), ('PZL', 'Puzzle'), ('SIM', 'Simulación'), ('PLT', 'Plataformas'), ('FAM', 'Familiar')], max_length=3)),
                ('fecha_lanzamiento', models.DateField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('editor', models.CharField(default='Nintendo', max_length=100)),
                ('desarrollador', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='videojuegos/')),
                ('calificacion_edad', models.CharField(default='E', max_length=5)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('consolas', models.ManyToManyField(related_name='videojuegos', to='nintendo.consola')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='personajes/')),
                ('biografia', models.TextField(blank=True)),
                ('es_protagonista', models.BooleanField(default=False)),
                ('primera_aparicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes_introducidos', to='nintendo.videojuego')),
                ('videojuegos', models.ManyToManyField(related_name='personajes', to='nintendo.videojuego')),
            ],
            options={
                'verbose_name_plural': 'Personajes',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('visualizaciones', models.PositiveIntegerField(default=0)),
                ('es_destacada', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('consolas_relacionadas', models.ManyToManyField(blank=True, related_name='noticias', to='nintendo.consola')),
                ('videojuegos_relacionados', models.ManyToManyField(blank=True, related_name='noticias', to='nintendo.videojuego')),
            ],
            options={
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('es_online', models.BooleanField(default=True)),
                ('enlace_stream', models.URLField(blank=True)),
                ('imagen', models.ImageField(upload_to='eventos/')),
                ('videojuegos_presentados', models.ManyToManyField(blank=True, related_name='eventos', to='nintendo.videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nintendo.consola')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nintendo.pedido')),
                ('videojuego', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nintendo.videojuego')),
            ],
        ),
    ]
